# -*- coding: utf-8 -*-
"""etl_hr_process.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pi4BMVVBjgyTUNmY6wsn2dD9jHKZp727
"""

import pandas as pd
import kagglehub
import os
import numpy as np

# --- 1. Extracción --
print("Descargando datos.")
path = kagglehub.dataset_download("nicolaszalazar73/ibm-hr-analytics-predictive-employee-attrition")
csv_file = [f for f in os.listdir(path) if f.endswith('.csv')][0]
df = pd.read_csv(os.path.join(path, csv_file))

print(f"Datos crudos cargados: {df.shape}")

# --- 2. Transformación y limpieza --
# a. Decodificación de variables
# En el dataset original, Education 1 = 'Below College', etc.
education_map = {
    1: 'Below College',
    2: 'College',
    3: 'Bachelor',
    4: 'Master',
    5: 'Doctor'
}
df['Education_Label'] = df['Education'].map(education_map)

# Mapeo de satisfacción (1=Low, 4=Very High)
satisfaction_map = {
    1: 'Low',
    2: 'Medium',
    3: 'High',
    4: 'Very High'
}
df['JobSatisfaction_Label'] = df['JobSatisfaction'].map(satisfaction_map)

# b. Ingeniería de características (crear nuevos KPIs)
# crear rangos de edad
bins_age = [0, 29, 45, 80]
labels_age = ['Junior (<30)', 'Mid-Level (30-45)', 'Senior (>45)']
df['Age_Group'] = pd.cut(df['Age'], bins=bins_age, labels=labels_age)

# crear rangos de salario (para ver si pagan mal)
# uso cuartiles para dividir en bajo, medio, alto automáticamente
df['Salary_Range'] = pd.qcut(df['MonthlyIncome'], q=3, labels=['Low Income', 'Medium Income', 'High Income'])

# c. Limpieza técnica
# eliminar columnas que no aportan valor al análisis
drop_cols = ['EmployeeCount', 'StandardHours', 'Over18', 'EmployeeNumber']
df_clean = df.drop(columns=drop_cols, errors='ignore')

df_clean.head()

# --- 3. Carga ---
df_clean.to_csv('HR_Analytics_Final.csv', index=False)
print("Transformación completada. Archivo 'HR_Analytics_Final.csv' generado.")